### ISSUE TITLE
Enable quarterly performance manager to submit quarterly updates to U.S. Performance Goals

### ISSUE THREAD

**Issue by metzgr** [GSA/US-performance-reporting#2]
## User story

As a Creator, 
I want to self-update my team's Performance.gov profile, 
so that I can keep my performance content current and accurate (and by extension meet the expectations of my stakeholders and audience).

## Acceptance criteria

Given 
When
Then I can see the new Profile Editor

## Tasks

* [ ] Review the current state in Touchpoints, for what exists for APG reporting
* [ ] Articulate the new features and goals of updating
* [ ] Design the future state of Touchpoints
* [ ] Implement the changes
* [ ] Ship the changes
* [ ] Get feedback on the changes
